theme: jekyll-theme-cayman
title: Learn German Today
description: Simple steps to learn German
github:
  grammar: grammar.html
  page3: vocabulary.html
  page4: useful-phrases.html
  page5: useful links.html
